# Generated by Django 5.2 on 2025-04-21 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Área de Interesse')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Área de Interesse')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Área de Interesse',
                'verbose_name_plural': 'Áreas de Interesse',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Enquete')),
                ('descricao', models.TextField(verbose_name='Descrição da Enquete')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_encerramento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Enquete',
                'verbose_name_plural': 'Enquetes',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Aluno')),
                ('email', models.EmailField(max_length=254, verbose_name='Email do Aluno')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('nivel_programacao', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], max_length=50, verbose_name='Nível de Programação')),
                ('linguagem_favorita', models.CharField(blank=True, max_length=100, null=True, verbose_name='Linguagem Favorita')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
                'unique_together': {('nome', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300, verbose_name='Texto da Pergunta')),
                ('tipo', models.CharField(choices=[('unica', 'Única Escolha'), ('multipla', 'Múltipla Escolha'), ('texto', 'Texto Livre')], max_length=20, verbose_name='Tipo de Resposta')),
                ('obrigatoria', models.BooleanField(default=True, verbose_name='Obrigatória')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.enquete', verbose_name='Enquete')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200, verbose_name='Texto da Opção')),
                ('valor', models.CharField(max_length=50, verbose_name='Valor da Opção')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.pergunta', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Opção',
                'verbose_name_plural': 'Opções',
                'ordering': ['ordem'],
                'unique_together': {('pergunta', 'valor')},
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(auto_now_add=True, verbose_name='Data da Resposta')),
                ('texto_livre', models.TextField(blank=True, null=True, verbose_name='Resposta Livre')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.aluno', verbose_name='Aluno')),
                ('opcao_unica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resposta_unica', to='perguntas.opcao', verbose_name='Opção Única')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.pergunta', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['-data_resposta'],
                'unique_together': {('aluno', 'pergunta')},
            },
        ),
        migrations.CreateModel(
            name='AlunoInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição')),
                ('nivel_interesse', models.IntegerField(default=1, verbose_name='Nível de Interesse')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.aluno', verbose_name='Aluno')),
                ('area_interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.areainteresse', verbose_name='Área de Interesse')),
            ],
            options={
                'verbose_name': 'Interesse do Aluno',
                'verbose_name_plural': 'Interesses dos Alunos',
                'unique_together': {('aluno', 'area_interesse')},
            },
        ),
        migrations.CreateModel(
            name='MultiplaEscolhaResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.opcao', verbose_name='Opção')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.resposta', verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Resposta Múltipla Escolha',
                'verbose_name_plural': 'Respostas Múltiplas Escolhas',
                'unique_together': {('resposta', 'opcao')},
            },
        ),
    ]
